# Data test
data = {
    "edu": [
      "Giáo dục là chìa khóa mở ra cánh cửa thành công trong cuộc đời.",
      "Giáo dục không chỉ giúp chúng ta có kiến thức mà còn rèn luyện tư duy logic.",
      "Giáo dục là nền tảng của một xã hội phát triển và thịnh vượng.",
      "Học hành không chỉ diễn ra trong trường học mà còn xảy ra trong cuộc sống hàng ngày.",
      "Một người học tập suốt đời sẽ không bao giờ cảm thấy mệt mỏi hay nhàm chán.",
      "Giáo dục là một cuộc chiến không bao giờ kết thúc giữa trí tuệ và sự ngu dốt.",
      "Học tập không chỉ để đạt được một bằng cấp mà còn để rèn luyện nhân cách.",
      "Giáo dục là con đường dẫn đến sự tự do và độc lập của con người.",
      "Trong giáo dục, sự tò mò và khám phá luôn là những động lực quan trọng.",
      "Giáo dục là sự đầu tư vào tương lai của chúng ta và xã hội.",
      "Giáo dục là chìa khóa mở ra cánh cửa tri thức",
      "Giáo dục là nền tảng cho sự phát triển bền vững của đất nước",
      "Giáo dục không chỉ là học vấn mà còn là cách sống",
      "Giáo dục giúp con người thấu hiểu thế giới xung quanh",
      "Giáo dục không giới hạn độ tuổi và không giới hạn thời gian",
      "Giáo dục cần phải được cập nhật và đổi mới liên tục",
      "Giáo dục không chỉ là truyền đạt kiến thức mà còn là truyền đạt giá trị",
      "Giáo dục đóng vai trò quan trọng trong việc hình thành nhân cách",
      "Giáo dục cần đào tạo ra nguồn nhân lực chất lượng cao",
      "Giáo dục là một quá trình không ngừng nghỉ trong cuộc đời",
  ],
  "health": [
      "Sức khỏe là tài sản quý giá nhất của con người.",
      "Có một tâm hồn khỏe mạnh là nền tảng của một cơ thể khỏe mạnh.",
      "Chăm sóc sức khỏe thường xuyên giúp ta tránh được nhiều căn bệnh nguy hiểm.",
      "Điều quan trọng nhất trong việc duy trì sức khỏe là thói quen ăn uống và sinh hoạt lành mạnh.",
      "Sức khỏe tốt giúp ta có thể đạt được mục tiêu trong cuộc sống.",
      "Chỉ cần một thói quen tốt, ta có thể cải thiện sức khỏe của mình rất nhiều.",
      "Để có một cơ thể khỏe mạnh, chúng ta cần vừa ăn uống đủ chất dinh dưỡng vừa tập thể dục thường xuyên.",
      "Sức khỏe không phải là điều kiện để sống, mà là cách để sống tốt hơn.",
      "Hạnh phúc và sức khỏe luôn đi đôi với nhau.",
      "Việc giữ gìn sức khỏe là trách nhiệm của chính chúng ta.",
      "Sức khỏe là tài sản quý giá nhất của con người.",
      "Hãy ăn uống đủ chất dinh dưỡng để duy trì sức khỏe tốt.",
      "Tập thể dục thường xuyên giúp cơ thể khỏe mạnh và tinh thần sảng khoái.",
      "Làm việc quá sức gây ảnh hưởng đến sức khỏe, hãy phân bổ thời gian hợp lý cho công việc và nghỉ ngơi.",
      "Ngủ đủ 7-8 tiếng mỗi ngày giúp cơ thể phục hồi và tái tạo năng lượng.",
      "Hút thuốc là nguyên nhân chính gây bệnh ung thư phổi và các bệnh lý khác, hãy từ bỏ thói quen này.",
      "Kiểm tra sức khỏe định kỳ giúp phát hiện sớm các bệnh lý và điều trị kịp thời.",
      "Hạn chế ăn đồ chiên, rán, nướng để giảm thiểu tác hại của chất béo động đến sức khỏe.",
      "Tránh uống rượu bia quá nhiều, vì nó gây hại đến gan và tác động đến sức khỏe tổng thể.",
      "Các bệnh lý tiểu đường, cao huyết áp, tim mạch đều có liên quan đến chế độ ăn uống và lối sống, hãy chú ý đến chúng.",
  ],
  "polution" :[
      "Ở đô thị, ô nhiễm môi trường là vấn đề cấp bách, người dân cần có những hành động cụ thể để bảo vệ sức khỏe của mình.",
      "Việc phát triển kinh tế đang đẩy mạnh các hoạt động công nghiệp, gây ra ô nhiễm môi trường nghiêm trọng và cần được khắc phục.",
      "Hạ tầng kém phát triển, công nghệ sản xuất lạc hậu và nhân thức chưa được nâng cao là những nguyên nhân gây ra ô nhiễm môi trường.",
      "Sự phát triển của các đô thị hiện nay đang gặp phải nhiều vấn đề về ô nhiễm môi trường, cần có giải pháp ngay để giảm thiểu tác động xấu đến cuộc sống con người.",
      "Các nguồn ô nhiễm môi trường như khói bụi, chất thải, hóa chất và các loại khí độc gây nguy hại đến sức khỏe con người.",
      "Tình trạng ô nhiễm môi trường đang ngày càng trầm trọng, gây ảnh hưởng không những đến sức khỏe con người mà còn đến sinh thái hệ địa phương và toàn cầu.",
      "Những nguyên nhân chính gây ra ô nhiễm môi trường là do hoạt động sản xuất, giao thông vận tải, xây dựng, đô thị hóa và sinh hoạt cá nhân.",
      "Việc sử dụng các nguồn năng lượng thay thế như năng lượng mặt trời, gió và nước là giải pháp hiệu quả để giảm thiểu ô nhiễm môi trường.",
      "Các quy định và chính sách về bảo vệ môi trường cần được áp dụng chặt chẽ và đầy đủ để giảm thiểu ô nhiễm môi trường.",
      "Hành động của mỗi cá nhân đều đóng góp vào việc giảm thiểu ô nhiễm môi trường, hãy cùng nhau chung tay bảo vệ môi trường xanh, sạch và đẹp.",
      "Ô nhiễm không khí gây hại cho sức khỏe của con người.",
      "Sông nước đang bị ô nhiễm nặng nề do công nghiệp và gia đình.",
      "Chất thải nhựa gây nên ô nhiễm môi trường lớn.",
      "Nạn ô nhiễm môi trường đang là mối đe dọa cho sinh thái và đời sống của con người.",
      "Việc tái chế là giải pháp hữu hiệu để giảm thiểu ô nhiễm môi trường.",
      "Thủy sản bị ô nhiễm gây hại cho sức khỏe người tiêu dùng.",
      "Việc phát thải khí thải gây ô nhiễm không khí đã trở thành một vấn đề lớn.",
      "Các loại chất độc hại trong nước thải có thể ảnh hưởng đến sức khỏe con người.",
      "Ô nhiễm môi trường là một vấn đề cần phải được xử lý nghiêm túc.",
      "Việc sử dụng năng lượng tái tạo là một giải pháp cho vấn đề ô nhiễm môi trường.",

  ],
  "startup": [
      "Khởi nghiệp là con đường để thực hiện đam mê và đạt được thành công lớn.",
      "Để khởi nghiệp thành công, ta cần có sự kiên trì, sáng tạo và tinh thần tự lập.",
      "Khởi nghiệp không đơn thuần là kinh doanh mà còn là một cuộc phiêu lưu tìm kiếm cơ hội và thử thách bản thân.",
      "Khởi nghiệp là cách để chúng ta tạo ra giá trị và có ảnh hưởng đến cộng đồng.",
      "Để thành công trong khởi nghiệp, ta cần có sự tỉ mỉ và kiên nhẫn trong từng bước đi.",
      "Khởi nghiệp không phải là con đường dễ dàng, nhưng nó đem lại cho ta sự tự do và độc lập trong công việc.",
      "Khởi nghiệp không chỉ là vấn đề tài chính mà còn cần sự quyết tâm và niềm đam mê không ngừng.",
      "Khởi nghiệp là con đường để chúng ta thể hiện tài năng và khả năng sáng tạo của mình.",
      "Thành công của một khởi nghiệp phụ thuộc vào khả năng tạo ra giá trị cho khách hàng.",
      "Sáng tạo và khả năng đổi mới là chìa khóa để thành công trong lĩnh vực khởi nghiệp.",
      "Khởi nghiệp không chỉ là việc bán sản phẩm hay dịch vụ, mà còn là việc giải quyết các vấn đề của xã hội.",
      "Thách thức lớn nhất của một khởi nghiệp là kiên trì vượt qua giai đoạn khởi đầu khó khăn.",
      "Một khởi nghiệp cần phải có ý tưởng sáng tạo và đội ngũ nhân viên đầy nhiệt huyết.",
      "Khởi nghiệp là con đường để tạo ra giá trị cho cộng đồng và xã hội.",
      "Việc đầu tư vào khởi nghiệp không chỉ là cách để kiếm lời, mà còn là sự đóng góp vào sự phát triển của xã hội.",
      "Một trong những yếu tố quan trọng của một khởi nghiệp thành công là khả năng thích ứng với thị trường.",
      "Tinh thần sáng tạo và kiên trì là chìa khóa để thành công trong việc khởi nghiệp.",
      "Một khởi nghiệp cần phải có một mô hình kinh doanh ổn định và đội ngũ quản lý chuyên nghiệp để phát triển và phát triển trong tương lai.",
      "Khởi nghiệp không chỉ đòi hỏi tư duy sáng tạo mà còn đòi hỏi kỹ năng quản lý và lãnh đạo.",
      "Thành công của một khởi nghiệp phụ thuộc vào việc giải quyết được vấn đề của khách hàng.",
  ],         
  "clothes": [
      "Áo sơ mi là một trong những item không thể thiếu trong tủ quần áo của bất kỳ chàng trai nào.",
      "Thiết kế của chiếc áo khoác này rất đặc biệt với những chi tiết đan xen giữa phong cách truyền thống và hiện đại.",
      "Trong những năm gần đây, thời trang unisex đang trở thành trào lưu hot trong giới trẻ.",
      "Bộ đồ thể thao không chỉ mang lại cảm giác thoải mái, dễ chịu khi tập luyện mà còn giúp bạn tự tin hơn trên phố.",
      "Đôi giày sneakers này không chỉ rất tiện dụng khi di chuyển mà còn có thiết kế phù hợp với nhiều hoàn cảnh khác nhau.",
      "Điểm nhấn của chiếc áo len này là màu sắc tươi sáng và họa tiết hoa văn độc đáo.",
      "Trang phục bó sát không chỉ giúp bạn khoe được những đường cong quyến rũ mà còn giúp bạn tự tin hơn trong mắt người đối diện.",
      "Túi xách là một trong những phụ kiện không thể thiếu cho phái đẹp. Chiếc túi này được làm từ chất liệu da cao cấp, tạo cảm giác sang trọng, đẳng cấp.",
      "Chất liệu denim của chiếc quần này rất đẹp và bền, tuy nhiên bạn cũng nên lưu ý về cách giặt và bảo quản để sản phẩm được bền lâu.",
      "Phong cách streetwear với chiếc hoodie này mang đến vẻ ngoài trẻ trung, cá tính cho bạn khi xuống phố.",
      "Mặc đẹp là phải có phong cách riêng.",
      "Có nhiều cách mix đồ để tạo nên phong cách thời trang.",
      "Hãy tìm cho mình một bộ trang phục vừa ấm áp vừa thoải mái để đón đầu mùa đông.",
      "Áo khoác denim là một trong những item không thể thiếu trong tủ đồ của mỗi người.",
      "Chọn đồ đúng cách sẽ giúp bạn tự tin hơn trong cuộc sống.",
      "Thời trang không chỉ là về quần áo, mà còn về phong cách sống.",
      "Không cần quá đắt tiền, chỉ cần biết cách mix đồ là bạn sẽ luôn thật sự lịch lãm.",
      "Cùng với thời trang, phụ kiện là một phần không thể thiếu trong bộ sưu tập của bạn.",
      "Hãy đầu tư cho những item quan trọng và phù hợp với phong cách của bạn.",
      "Nếu không biết mặc gì, hãy chọn những item cơ bản và dễ phối đồ như áo trắng, quần jean.",
  ],
  "history": [
      "Năm 1947, Kế hoạch Marshall được đưa ra để hỗ trợ châu Âu phục hồi sau Thế chiến thứ hai.",
      "Năm 1776, Tuyên ngôn độc lập Hoa Kỳ được ký kết.",
      "Năm 1991, Liên Xô tan rã và kết thúc Chiến tranh Lạnh.",
      "Năm 1688, Cách mạng dân chủ Anh diễn ra, đưa quyền lực của vua vào giới hạn.",
      "Năm 1865, Nô lệ bị giải phóng tại Hoa Kỳ sau Thế chiến thứ nhất.",
      "Công cuộc giải phóng dân tộc Việt Nam vào năm 1975 đã đánh dấu một trang sử mới trong lịch sử đất nước.",
      "Cuộc kháng chiến chống Mỹ của nhân dân Việt Nam đã góp phần lớn vào thắng lợi của cuộc chiến tranh giành độc lập và thống nhất đất nước.",
      "Thế kỷ 19 là thời kỳ phát triển của chủ nghĩa thực dân và bùng nổ của phong trào cách mạng dân tộc.",
      "Cuộc cách mạng tháng Mười Nga năm 1917 đã đánh dấu một sự kiện lớn của thế giới và là động lực cho các phong trào cách mạng khác trên thế giới.",
      "Công nguyên là một thời kỳ rất quan trọng trong lịch sử Trung Quốc.",
      "Triều đại Trần là một triều đại lịch sử quan trọng của Việt Nam.",
      "Chiến tranh thế giới thứ hai là cuộc chiến lớn nhất trong lịch sử loài người.",
      "Năm 1968 là một năm đầy biến động trong lịch sử thế giới.",
      "Cách mạng công nghiệp đã thay đổi hoàn toàn nền kinh tế thế giới.",
      "Năm 1789, Cách mạng Pháp đã đánh dấu sự khởi đầu của thời kỳ mới trong lịch sử châu Âu.",
      "Tôn Trung Sơn là một trong những vị tướng xuất sắc nhất trong lịch sử Trung Quốc.",
      "Năm 1954, Điện Biên Phủ đã chứng minh sức mạnh của quân dân Việt Nam và đánh dấu một bước ngoặt quan trọng trong lịch sử Việt Nam.",
      "Năm 1917, Cách mạng tháng Mười Nga đã đánh dấu sự khởi đầu của sự lên ngôi của chủ nghĩa xã hội trong lịch sử nhân loại.",
      "Năm 1865, Thống nhất nước Mỹ đã đánh dấu sự kết thúc của cuộc nội chiến và sự thống nhất của đất nước.",
      "Sự kiện Khiêu chiến tranh bị đánh bại vào năm 1894 đã đánh dấu sự suy yếu của chế độ phong kiến trước cuộc tấn công của các thế lực thực dân phương Tây.",
  ],    
}

